/*
	  * Please do not edit this file.
		 * It was generated using rpcgen.
		  */

#ifndef _RPC_KV_H_RPCGEN
#define _RPC_KV_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


				struct row {
									int key;
										char value[25];
				};
				typedef struct row row;

#define KEYVAL_PROG 0x32345678
#define KEYVAL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PUT 1
				extern  enum clnt_stat put_1(row *, bool_t *, CLIENT *);
				extern  bool_t put_1_svc(row *, bool_t *, struct svc_req *);
#define GET 2
				extern  enum clnt_stat get_1(int *, char **, CLIENT *);
				extern  bool_t get_1_svc(int *, char **, struct svc_req *);
#define DELETE 3
				extern  enum clnt_stat delete_1(int *, bool_t *, CLIENT *);
				extern  bool_t delete_1_svc(int *, bool_t *, struct svc_req *);
				extern int keyval_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PUT 1
				extern  enum clnt_stat put_1();
				extern  bool_t put_1_svc();
#define GET 2
				extern  enum clnt_stat get_1();
				extern  bool_t get_1_svc();
#define DELETE 3
				extern  enum clnt_stat delete_1();
				extern  bool_t delete_1_svc();
				extern int keyval_prog_1_freeresult ();
#endif /* K&R C */

				/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
				extern  bool_t xdr_row (XDR *, row*);

#else /* K&R C */
				extern bool_t xdr_row ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_KV_H_RPCGEN */
