/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 * Edited By Jayant Gupta
 * Date : Nov 1, 2015
 */

#include "rpc_kv.h"
#include "keyval.h"

bool_t *
put_1_svc(row *argp, struct svc_req *rqstp)
{
	char *name = "word_list.txt";
	init_dict(name);
	static bool_t  result;
	result = _PUT(argp->key, argp->value);

	/*
	 * insert server code here
	 */

	return &result;
}

char **
get_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;
	result = _GET(*argp);

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
delete_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	result = _DELETE(*argp);

	/*
	 * insert server code here
	 */

	return &result;
}
