/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 * Edited by Jayant Gupta
 * Date Nov 1, 2015
 */

#include "rpc_kv.h"

void 
keyval_prog_1(char *host, char *cmd);

int
main (int argc, char *argv[])
{
	printf("Command format : <GET:INDEX> ; <PUT:Index:Value> ; <DELETE:Index>\n");
	char *host;
	char *cmd;
	if (argc < 3) {
		printf ("usage: %s server_host command\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	cmd = argv[2];
	keyval_prog_1(host, cmd);
	exit (0);
	return 0;
}

void
keyval_prog_1(char *host, char *cmd)
{
	CLIENT *clnt;
	bool_t  *result_1;
	row  put_1_arg;
	char * *result_2;
	int  get_1_arg;
	bool_t  *result_3;
	int  delete_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, KEYVAL_PROG, KEYVAL_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	const char *delim = ":";
	char *token = strtok(cmd, delim);
	int count = 0;
	char args[3][25];
	while(token != NULL){
		strcpy(args[count], token);
		count += 1;
		token = strtok(NULL, delim);
		printf("token: %s\n",token);
	}
	
	if(strcmp(args[0], "PUT") == 0){
		put_1_arg.key = atoi(args[1]);
		strcpy(put_1_arg.value, args[2]);
		result_1 = put_1(&put_1_arg, clnt);
		if (result_1 == (bool_t *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("Result of PUT request %d\n", *result_1);
	}

	if(strcmp(args[0],"GET") == 0){
		get_1_arg = atoi(args[1]);
		result_2 = get_1(&get_1_arg, clnt);
		if (result_2 == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("Result of DELETE request %s\n", *result_2);
	}

	if(strcmp(args[0], "DELETE") == 0){
		delete_1_arg = atoi(args[1]);
		result_3 = delete_1(&delete_1_arg, clnt);
		if (result_3 == (bool_t *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("Result of PUT request %d\n", *result_3);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return;
}
