/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

/* TODO : Add Locks */

#include "rpc_kv.h"
#include "keyval.h"

bool_t
put_1_svc(row *argp, bool_t *result, struct svc_req *rqstp)
{
	printf("Inside PUT Request\n");
	*result = _PUT(argp->key,argp->value);
	return(TRUE);
}

bool_t
get_1_svc(int *argp, char **result, struct svc_req *rqstp)
{
	printf("%d\n", *argp);
	printf("Inside GET Request\n");
	*result = (char *)malloc(sizeof(char)*26);
	strcpy(*result, _GET(*argp));
	printf("%s\n",*result);
	return(TRUE);
}

bool_t
delete_1_svc(int *argp, bool_t *result, struct svc_req *rqstp)
{
	printf("Inside DELETE request\n");
	*result = _DELETE(*argp);
	return(TRUE);
}

int
keyval_prog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);
	return 1;
}
