/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_kv.h"

bool_t
xdr_row (XDR *xdrs, row *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->value, 25,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
